# Check out https://docs.codemagic.io/getting-started/building-a-react-native-app/ for more information
# Please review and update values in curly braces

workflows:
    react-native:
        name: React Native App
        environment:
            vars:
                XCODE_WORKSPACE: "HelloCodemagic"
                XCODE_SCHEME: "HelloCodemagic"
            node: latest
        scripts:
            - npm install
            - echo "sdk.dir=$HOME/programs/android-sdk-macosx" > "$FCI_BUILD_DIR/android/local.properties"
            - |
                # build Android
                cd android
                ./gradlew assembleRelease
                cd $FCI_BUILD_DIR/android/app/build/outputs/apk/release
                curl -H "Authorization: token d5768523-3641-4804-b6e9-35040fd6da73" -F "file=@app-release.apk" -F "message=test2" "https://deploygate.com/api/users/thanhhv_neos/apps"